### ISSUE TITLE
Errors adding lambda permissions for cloudwatch event rules

### ISSUE THREAD

**Issue by mikesnare** [moritzzimmer/terraform-aws-lambda#128]
We are using this module to create a number of lambdas and the majority of the lambdas have 2-4 event bridge rules in place.  Lately I've been noticing that the first attempt to run our terraform scripts in a new environment are failing, and they always fail with the same error:

```
Error: adding Lambda Permission (<FUNCTION_NAME>/terraform-<WHATEVER>): ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:<ACCOUNT_ID>:function:<FUNCTION_NAME>
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "78582a61-1eb8-45e2-b8d1-68b40c11def0"
 },
  Message_: "Function not found: arn:aws:lambda:us-east-1:<ACCOUNT_ID>:function:<FUNCTION_NAME>",
  Type: "User"
}

  with module.event-bridge-lambdas[<INTERNAL_LAMBDA_NAME>].module.lambda.aws_lambda_permission.cloudwatch_events[<EVENT_NAME>],
  on .terraform/modules/event-bridge-lambdas.lambda/cloudwatch_event_rules.tf line 1, in resource "aws_lambda_permission" "cloudwatch_events":
   1: resource "aws_lambda_permission" "cloudwatch_events"
```

We have 6 lambdas being created by this module and the most recent run had 5 fail with this error.  However, after checking the lambdas in AWS I see that all 6 were created successfully -- some are just missing some of the EB rules to trigger them.

What I've also noticed is that if I immediately re-run the apply following this error, everything works fine.  So it _seems_ like one of 2 things may be happening:

1. Maybe there's a timeout during the lambda creation and the code just moves on, attempting the next step?
2. Maybe there's some eventual-consistency issue in AWS itself that means that immediately following the successful creation of a lambda additional requests to create resources that rely on those lambdas can't succeed?

I'm not sure which of those (or something else entirely...) it might be, so I figured I'd start here and see if there are any known issues of this kind.

Thanks in advance for any help.

**Comment by moritzzimmer** [comment]
@mikesnare could you provide an example configuration to test this issue?

**Comment by elliottohara** [comment]
@moritzzimmer , meet @mikesnare , @mikesnare  meet @moritzzimmer ! 

PR for this incoming. @moritzzimmer ... We're just using a string for the function name in `cloudwatch_event_rules` should instead reference the lambda and get it's name instead. It's just a race condition that's aggravated for us because our lambdas take longer to create.
